name: sleep-pain-coupling
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pymc=5.27.1
  - arviz=0.23.4
  - numpy=2.3.2
  - scipy=1.16.1
  - pandas=2.3.1
  - matplotlib=3.10.5
  - openpyxl=3.1.5
  - pillow=11.3.0
  - scikit-learn=1.7.1
  - pytensor
  - nibabel>=5.2
