#!/usr/bin/env python3
"""
generate_synthetic_data.py
==========================
Parametric synthetic data generator for the quarterly sleep-pain coupling
analysis pipeline.

This script generates simulated data that mirrors the structure of the real
UPLOAD2 knee-pain cohort so the full Python analysis pipeline can run
end-to-end without access to restricted participant data.

The ground-truth parameters are taken directly from the manuscript
(Tables 3-5) and reproduce the key statistical signatures of the real data:
bidirectional coupling, contrast-factor moderation, left-NAcc moderation of
the sleep-to-pain path, and null age/sex moderation.

Model
-----
The data-generating process is a Vector Autoregressive model with exogenous
input, order 1 — a VARX(1).  At each quarterly transition, two within-person
centered variables (pain severity and sleep quality) are predicted from their
own lagged values and from a time-varying exogenous contrast factor (kappa).

Let  p_w(t) = within-person centered pain at quarter t
     s_w(t) = within-person centered sleep at quarter t
     K(t)   = within-person centered contrast factor at quarter t

The two equations are:

  Pain equation:
    p_w(t) = mu_p
           + phi_p      * p_w(t-1)          [pain autoregression]
           + lambda_sp_i * s_w(t-1)          [sleep -> pain coupling]
           + delta_p     * K(t-1)            [contrast direct effect on pain]
           + omega_sp    * s_w(t-1) * K(t-1) [sleep x contrast interaction]
           + epsilon_p(t)

  Sleep equation:
    s_w(t) = mu_s
           + lambda_ps_i * p_w(t-1)          [pain -> sleep coupling]
           + phi_s       * s_w(t-1)          [sleep autoregression]
           + delta_s     * K(t-1)            [contrast direct effect on sleep]
           + omega_ps    * p_w(t-1) * K(t-1) [pain x contrast interaction]
           + epsilon_s(t)

The coupling coefficients are person-specific:

  lambda_sp_i = lambda_sp
              + gamma_sp_age * Age_z_i
              + gamma_sp_sex * Sex_c_i
              + u_sp_i

  lambda_ps_i = lambda_ps
              + gamma_ps_age * Age_z_i
              + gamma_ps_sex * Sex_c_i
              + u_ps_i

where u_sp_i ~ N(0, tau_sp^2) and u_ps_i ~ N(0, tau_ps^2) are random effects.

Correlated Innovations (the Cholesky Trick)
--------------------------------------------
In a bivariate system the innovation terms (residuals) of the two equations
may be contemporaneously correlated.  If a person has an unexpectedly bad
pain day, they may also have unexpectedly poor sleep that same quarter.
We model this with a 2x2 covariance matrix:

  Sigma = | sigma_p^2                   rho*sigma_p*sigma_s |
          | rho*sigma_p*sigma_s         sigma_s^2           |

To draw correlated innovations efficiently, we use the Cholesky
decomposition.  Instead of sampling from a 2-d multivariate normal (which
requires constructing and inverting the full covariance matrix each time),
we draw two independent standard normals z1, z2 and transform them:

  epsilon_p = sigma_p * z1
  epsilon_s = rho * sigma_s * z1  +  sigma_s * sqrt(1 - rho^2) * z2

This is algebraically identical to sampling from MVN(0, Sigma) but is
~100x faster in a loop.  The same trick is used in the PyMC estimation
model.

Within-Person Centering
-----------------------
The real analysis pipeline works with within-person centered data: each
person's time series is demeaned so that between-person differences in
mean pain level or mean sleep quality are removed.  This eliminates the
need for random intercepts and between-person covariates, isolating the
*dynamics* (how changes in sleep predict changes in pain, and vice versa).

In this generator, we simulate the *raw* (uncentered) time series first,
then apply within-person centering post-hoc, exactly as done with the
real data.  The raw series are generated by initializing each person's
first observation from a reasonable marginal distribution and then
iterating the VARX(1) forward.  After centering, the first usable
"transition" for each person starts at t=1 (lag from t=0 to t=1).

References
----------
[1] Valdes-Hernandez PA et al. (2026). Quarterly Sleep-Pain Coupling in
    Knee Pain. [manuscript in preparation]
[2] Hamilton JD. Time Series Analysis. Princeton University Press, 1994.
    — Chapter 11: Vector autoregressive models.
[3] Bolger N, Laurenceau JP. Intensive Longitudinal Methods. Guilford, 2013.
    — Within-person centering for diary/EMA designs.

Usage
-----
  python simulate/generate_synthetic_data.py [--seed 42]

Outputs (relative to repository root):
  data/synthetic/quarterly_data_long.csv
  data/synthetic/participants_wideformat.csv
  data/synthetic/roi_values.csv
  data/synthetic/vbm_volumes.csv
  data/synthetic/ground_truth.json
"""

import argparse
import json
import os

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# 0.  Repository path setup
# ---------------------------------------------------------------------------
# Determine the repository root (one level up from the simulate/ directory).
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT_DIR = os.path.join(REPO_ROOT, "data", "synthetic")


# ===========================================================================
# 1.  GROUND-TRUTH PARAMETERS
# ===========================================================================
# Every number below comes from the manuscript tables.  Comments reference
# the table and column so a reader can trace each value back to the paper.

# --- VARX(1) population-level fixed effects (Table 4) ---------------------
PARAMS = {
    # Pain equation
    "mu_p":       0.009,   # Intercept, pain equation
    "phi_p":      0.106,   # Autoregressive coefficient, pain
    "lambda_sp": -0.021,   # Cross-lag coupling: sleep(t-1) -> pain(t)
    "delta_p":    0.024,   # Direct effect of contrast factor on pain
    "omega_sp":   0.009,   # Interaction: sleep(t-1) x contrast(t-1) -> pain

    # Sleep equation
    "mu_s":       0.004,   # Intercept, sleep equation
    "lambda_ps": -0.140,   # Cross-lag coupling: pain(t-1) -> sleep(t)
    "phi_s":      0.004,   # Autoregressive coefficient, sleep
    "delta_s":   -0.050,   # Direct effect of contrast factor on sleep
    "omega_ps":  -0.050,   # Interaction: pain(t-1) x contrast(t-1) -> sleep

    # Random-effect SDs (posterior means from Table 4)
    "tau_sp":     0.115,   # SD of person-specific sleep->pain coupling
    "tau_ps":     0.362,   # SD of person-specific pain->sleep coupling

    # Innovation (residual) parameters
    "sigma_p":    0.437,   # SD of pain innovation
    "sigma_s":    0.661,   # SD of sleep innovation
    "rho":       -0.155,   # Contemporaneous correlation of innovations
    #   rho < 0 means: quarters where pain is unexpectedly high tend to
    #   also have unexpectedly *better* sleep quality (or vice versa).
    #   This is a within-quarter association after accounting for all
    #   lagged predictors.

    # Age/sex moderation of coupling (Table 4, all null)
    "gamma_sp_age":  0.006,   # Age moderation of sleep->pain coupling
    "gamma_sp_sex":  0.006,   # Sex moderation of sleep->pain coupling
    "gamma_ps_age": -0.024,   # Age moderation of pain->sleep coupling
    "gamma_ps_sex": -0.011,   # Sex moderation of pain->sleep coupling
}

# --- Demographic distributions (Table 3) ----------------------------------
DEMO = {
    "N":            229,       # Total sample size
    "age_mean":     58.1,      # Mean age in years
    "age_sd":        8.2,      # SD of age
    "age_min":      31,        # Minimum age
    "age_max":      79,        # Maximum age
    "pct_female":    0.646,    # 148F / 229 = 64.6%
    # Race distribution (Table 3)
    "race_probs": {            # Probabilities for multinomial draw
        "Black":    0.397,
        "White":    0.293,
        "Hispanic": 0.240,
        "Other":    0.070,
    },
}

# --- Timepoint distribution ------------------------------------------------
# Empirical distribution: median = 9 quarters, range 2-10.
# We approximate this with a left-skewed discrete distribution on {2,...,10}.
# The probabilities below were calibrated so that:
#   - median = 9
#   - total transitions ~ 1818  (229 people x ~7.9 transitions each)
#   - no one has fewer than 2 or more than 10 timepoints
TIMEPOINT_VALUES = np.arange(2, 11)  # 2, 3, ..., 10
TIMEPOINT_PROBS = np.array([
    0.01,   # 2 timepoints  (rare — most people stayed in the study)
    0.01,   # 3
    0.02,   # 4
    0.02,   # 5
    0.03,   # 6
    0.04,   # 7
    0.06,   # 8
    0.31,   # 9  (median)
    0.50,   # 10 (mode — majority completed all visits)
])
TIMEPOINT_PROBS = TIMEPOINT_PROBS / TIMEPOINT_PROBS.sum()  # normalize

# --- fMRI subsample and ROI moderation (Table 5) --------------------------
N_FMRI = 174   # Subsample with task-fMRI data

# Sleep-to-pain (SP) moderation gammas for each fMRI ROI.
# The key finding is that left NAcc and right dACC/MCC significantly
# moderate the sleep-to-pain coupling path.
FMRI_SP_GAMMAS = {
    # Krause et al. (2019) pain-relevant ROIs
    "Right_S1":            -0.017,   # Null
    "Right_Mid_Insula":     0.018,   # Null
    "Left_Thalamus":        0.013,   # Null
    "Left_Ant_Insula":      0.006,   # Null
    "Left_NAcc":            0.040,   # ** Significant (p=0.027) **
    "Right_NAcc":           0.023,   # Same direction, null (p=0.194)
    # Sardi et al. (2023) motivated ACC ROI
    "Right_dACC_MCC":       0.038,   # * Significant (p=0.047) *
    # Lynch et al. (2025) arousal ROIs (fMRI BOLD) — all null for SP
    "PBN":                  0.000,   # Parabrachial nucleus
    "SI_BF_Ch4":            0.030,   # Substantia innominata / basal forebrain
    "CeA":                  0.016,   # Central amygdala
    "BNST":                 0.019,   # Bed nucleus of the stria terminalis
    "LH":                   0.000,   # Lateral hypothalamus (not tested for SP)
}

# To make the significant ROIs recoverable, we embed correlations between
# the ROI z-score and the person-specific random effect u_sp.
# For null ROIs, correlation = 0 (independent of random effects).
FMRI_SP_CORR_WITH_U_SP = {
    "Left_NAcc":        0.25,   # Modest correlation -> recoverable gamma
    "Right_dACC_MCC":   0.20,   # Slightly weaker
    # All others: 0.0 (no embedded correlation)
}

# Pain-to-sleep (PS) moderation gammas for VBM arousal ROIs.
# Lynch et al. (2025) arousal ROIs, gray matter volume — all null
# individually, but 5/5 sign concordance (p=0.031).
VBM_PS_GAMMAS = {
    "PBN":      -0.062,   # Strongest negative, still null
    "SI_BF_Ch4": 0.022,
    "CeA":       0.073,
    "BNST":     -0.077,
    "LH":       -0.040,   # Approximate (similar to BNST direction)
}


# ===========================================================================
# 2.  HELPER FUNCTIONS
# ===========================================================================

def generate_demographics(rng, n, demo):
    """
    Generate a demographics table for n simulated participants.

    Parameters
    ----------
    rng : numpy.random.Generator
        Random number generator (for reproducibility).
    n : int
        Number of participants.
    demo : dict
        Demographic distribution parameters.

    Returns
    -------
    pd.DataFrame
        Columns: subject_id, age, sex, race, age_z, sex_c
        - age: continuous, truncated to [age_min, age_max]
        - sex: 0 = male, 1 = female
        - race: categorical string
        - age_z: z-scored age (mean 0, SD 1)
        - sex_c: centered sex (sex - proportion female)
    """
    # --- Age ---
    # Draw from a normal distribution and clip to the observed range.
    # The truncation is mild (the range is ~6 SDs wide) so the resulting
    # distribution is nearly Gaussian.
    ages = rng.normal(demo["age_mean"], demo["age_sd"], size=n)
    ages = np.clip(ages, demo["age_min"], demo["age_max"])

    # --- Sex ---
    # Bernoulli draw: 1 = female with probability pct_female.
    sex = rng.binomial(1, demo["pct_female"], size=n)

    # --- Race ---
    # Multinomial draw from the four categories.
    race_categories = list(demo["race_probs"].keys())
    race_probabilities = list(demo["race_probs"].values())
    race = rng.choice(race_categories, size=n, p=race_probabilities)

    # --- Centering ---
    # Age is z-scored (subtract sample mean, divide by sample SD) so that
    # the moderation coefficients are interpretable as "effect per SD of age."
    age_z = (ages - ages.mean()) / ages.std()
    # Sex is mean-centered so that the main coupling effects (lambda_sp,
    # lambda_ps) are evaluated at the sample-average sex composition,
    # not at sex=0 (i.e., not "for males only").
    sex_c = sex - sex.mean()

    df = pd.DataFrame({
        "subject_id": [f"sub-{i+1:03d}" for i in range(n)],
        "age":        np.round(ages, 1),
        "sex":        sex,
        "race":       race,
    })
    # We return the centered versions separately (used in simulation but
    # not saved to the demographics file — the analysis pipeline recomputes
    # them from raw age and sex).
    return df, age_z, sex_c


def generate_timepoints(rng, n):
    """
    Draw number of quarterly timepoints for each participant.

    Most participants completed all 10 visits (40 months of follow-up).
    The distribution is left-skewed, with a few people having as few as 2.

    Parameters
    ----------
    rng : numpy.random.Generator
    n : int

    Returns
    -------
    np.ndarray of int, shape (n,)
        Number of timepoints per person (between 2 and 10).
    """
    n_timepoints = rng.choice(TIMEPOINT_VALUES, size=n, p=TIMEPOINT_PROBS)
    return n_timepoints


def simulate_varx1(rng, n_t, params, age_z_i, sex_c_i, u_sp_i, u_ps_i):
    """
    Simulate one person's quarterly time series from the VARX(1) model.

    This function iterates the bivariate VAR forward in time, generating
    raw (uncentered) pain and sleep values plus a contrast factor series.

    Parameters
    ----------
    rng : numpy.random.Generator
    n_t : int
        Number of timepoints for this person (including t=0 initial value).
    params : dict
        Population-level parameters.
    age_z_i : float
        This person's z-scored age.
    sex_c_i : float
        This person's centered sex.
    u_sp_i : float
        This person's random effect on the sleep->pain coupling path.
    u_ps_i : float
        This person's random effect on the pain->sleep coupling path.

    Returns
    -------
    pain : np.ndarray, shape (n_t,)
        Simulated pain severity (raw, before within-person centering).
    sleep : np.ndarray, shape (n_t,)
        Simulated sleep quality (raw, before within-person centering).
    contrast : np.ndarray, shape (n_t,)
        Contrast factor values (time-varying exogenous predictor).
    """
    # Unpack parameters for readability
    mu_p      = params["mu_p"]
    phi_p     = params["phi_p"]
    lambda_sp = params["lambda_sp"]
    delta_p   = params["delta_p"]
    omega_sp  = params["omega_sp"]
    mu_s      = params["mu_s"]
    lambda_ps = params["lambda_ps"]
    phi_s     = params["phi_s"]
    delta_s   = params["delta_s"]
    omega_ps  = params["omega_ps"]
    sigma_p   = params["sigma_p"]
    sigma_s   = params["sigma_s"]
    rho       = params["rho"]
    g_sp_age  = params["gamma_sp_age"]
    g_sp_sex  = params["gamma_sp_sex"]
    g_ps_age  = params["gamma_ps_age"]
    g_ps_sex  = params["gamma_ps_sex"]

    # --- Person-specific coupling coefficients ---
    # These are constant across time for a given person (the random effects
    # and demographics don't change across quarters).  The omega*K interaction
    # term is added inside the loop because K varies over time.
    lambda_sp_base = lambda_sp + g_sp_age * age_z_i + g_sp_sex * sex_c_i + u_sp_i
    lambda_ps_base = lambda_ps + g_ps_age * age_z_i + g_ps_sex * sex_c_i + u_ps_i

    # --- Contrast factor ---
    # The contrast factor kappa captures localized vs. widespread pain.
    # It is derived from a 2-factor model of quarterly pain items.
    # In the real data it is approximately standard normal within-person.
    # We generate it as iid N(0, 1) for simplicity; within-person centering
    # later will ensure mean 0 per person.
    contrast = rng.normal(0, 1, size=n_t)

    # --- Initialize time series ---
    pain  = np.zeros(n_t)
    sleep = np.zeros(n_t)

    # Initial values (t=0): draw from a marginal distribution.
    # Since the within-person-centered variables have mean ~0 and SD ~0.5-0.7,
    # we initialize from N(0, sigma) for each.  These initial values will be
    # absorbed by the within-person centering step; they don't affect the
    # estimated coupling parameters.
    pain[0]  = rng.normal(0, sigma_p)
    sleep[0] = rng.normal(0, sigma_s)

    # --- Forward iteration ---
    # For each subsequent timepoint, compute the predicted value from the
    # lagged predictors plus a correlated innovation.
    for t in range(1, n_t):
        # Lagged values
        p_lag = pain[t - 1]
        s_lag = sleep[t - 1]
        k_lag = contrast[t - 1]

        # Time-varying coupling (includes contrast interaction)
        # The omega terms capture how the coupling changes as a function of
        # pain localization: when kappa is high (more widespread pain),
        # the coupling may strengthen or weaken.
        lambda_sp_t = lambda_sp_base + omega_sp * k_lag
        lambda_ps_t = lambda_ps_base + omega_ps * k_lag

        # Deterministic (predicted) component of each equation
        pain_pred  = mu_p + phi_p * p_lag + lambda_sp_t * s_lag + delta_p * k_lag
        sleep_pred = mu_s + lambda_ps_t * p_lag + phi_s * s_lag + delta_s * k_lag

        # --- Correlated innovations via Cholesky decomposition ---
        #
        # We need:
        #   [epsilon_p]   ~  MVN( [0], [sigma_p^2              rho*sigma_p*sigma_s] )
        #   [epsilon_s]        ( [0], [rho*sigma_p*sigma_s     sigma_s^2          ] )
        #
        # The Cholesky factor L of the 2x2 covariance matrix is:
        #   L = [sigma_p,         0                        ]
        #       [rho*sigma_s,     sigma_s*sqrt(1-rho^2)    ]
        #
        # So: [epsilon_p, epsilon_s]^T = L @ [z1, z2]^T
        #   where z1, z2 ~ N(0, 1) independently.
        #
        # Expanding:
        #   epsilon_p = sigma_p * z1
        #   epsilon_s = rho * sigma_s * z1  +  sigma_s * sqrt(1 - rho^2) * z2
        #
        # This gives the correct marginal variances and cross-covariance,
        # and avoids the overhead of constructing a 2x2 matrix each iteration.

        z1 = rng.standard_normal()
        z2 = rng.standard_normal()

        eps_p = sigma_p * z1
        eps_s = rho * sigma_s * z1 + sigma_s * np.sqrt(1 - rho**2) * z2

        pain[t]  = pain_pred + eps_p
        sleep[t] = sleep_pred + eps_s

    return pain, sleep, contrast


def within_person_center(values):
    """
    Subtract the person's own mean from a time series.

    Within-person centering removes stable between-person differences
    (e.g., one person always rates pain higher than another) and isolates
    the *fluctuations* around each person's own average.  This is the
    standard preprocessing step in intensive longitudinal designs
    (Bolger & Laurenceau, 2013).

    After centering, the mean of each person's series is exactly 0,
    so random intercepts are unnecessary in the estimation model.

    Parameters
    ----------
    values : np.ndarray
        Raw time series for one person.

    Returns
    -------
    np.ndarray
        Centered time series (same length, mean = 0).
    """
    return values - values.mean()


def generate_fmri_rois(rng, n_fmri, u_sp, fmri_indices):
    """
    Generate z-scored fMRI BOLD ROI values for the fMRI subsample.

    For most ROIs, the values are simply drawn from N(0,1) — they have no
    true relationship with the coupling random effects, so the estimated
    moderation gamma should be null.

    For the two ROIs with significant moderation (left NAcc and right
    dACC/MCC), we embed a correlation between the ROI z-score and the
    person's random effect u_sp_i.  This ensures that when the analysis
    model estimates gamma_sp for these ROIs, it will recover a nonzero
    value, reproducing the key finding.

    The embedded correlation is achieved by constructing the ROI value as
    a weighted combination of the random effect (signal) and independent
    noise.  If the target correlation is r, then:

        roi_value = r * u_sp_z + sqrt(1 - r^2) * noise

    where u_sp_z is the z-scored random effect and noise ~ N(0,1).
    This gives  corr(roi, u_sp) = r  exactly (in expectation).

    Parameters
    ----------
    rng : numpy.random.Generator
    n_fmri : int
        Number of participants in the fMRI subsample.
    u_sp : np.ndarray, shape (N_total,)
        Sleep-to-pain random effects for all participants.
    fmri_indices : np.ndarray of int, shape (n_fmri,)
        Indices into the full sample identifying fMRI participants.

    Returns
    -------
    pd.DataFrame
        Long-format: subject_id, roi_name, bold_value
    """
    # Z-score the random effects for the fMRI subsample
    u_sp_sub = u_sp[fmri_indices]
    u_sp_z = (u_sp_sub - u_sp_sub.mean()) / u_sp_sub.std()

    rows = []
    for roi_name in FMRI_SP_GAMMAS:
        # Check if this ROI has an embedded correlation
        r = FMRI_SP_CORR_WITH_U_SP.get(roi_name, 0.0)

        if r > 0:
            # Signal + noise mixture to achieve target correlation
            noise = rng.standard_normal(n_fmri)
            roi_values = r * u_sp_z + np.sqrt(1 - r**2) * noise
        else:
            # Pure noise — no relationship with random effects
            roi_values = rng.standard_normal(n_fmri)

        # Z-score the final ROI values (analysis pipeline expects z-scored)
        roi_values = (roi_values - roi_values.mean()) / roi_values.std()

        for j in range(n_fmri):
            rows.append({
                "subject_id": f"sub-{fmri_indices[j]+1:03d}",
                "roi_name":   roi_name,
                "bold_value": round(float(roi_values[j]), 6),
            })

    return pd.DataFrame(rows)


def generate_vbm_volumes(rng, n_fmri, u_ps, fmri_indices):
    """
    Generate gray matter volume values for VBM arousal ROIs.

    In the real data, none of the VBM arousal ROI volumes significantly
    moderated the pain-to-sleep coupling path individually (all p > 0.05).
    However, there was a notable sign concordance: all 5 gamma_ps estimates
    were negative (binomial p = 0.031), suggesting a weak but consistent
    directional effect.

    We generate these as independent standard normal values with a very
    slight negative correlation with u_ps to preserve the sign pattern,
    but not strong enough for any individual ROI to reach significance.

    Parameters
    ----------
    rng : numpy.random.Generator
    n_fmri : int
    u_ps : np.ndarray, shape (N_total,)
        Pain-to-sleep random effects for all participants.
    fmri_indices : np.ndarray of int

    Returns
    -------
    pd.DataFrame
        Long-format: subject_id, roi_name, gm_volume
    """
    # Z-score the pain-to-sleep random effects for the fMRI subsample
    u_ps_sub = u_ps[fmri_indices]
    u_ps_z = (u_ps_sub - u_ps_sub.mean()) / u_ps_sub.std()

    rows = []
    for roi_name, gamma in VBM_PS_GAMMAS.items():
        # Embed a very weak correlation in the direction of gamma
        # to preserve the sign concordance pattern.
        # We use r = sign(gamma) * 0.08 — weak enough to be individually
        # null but consistent across ROIs.
        r = np.sign(gamma) * 0.08

        noise = rng.standard_normal(n_fmri)
        vol_values = r * u_ps_z + np.sqrt(1 - r**2) * noise

        # Scale to a plausible GM volume range (arbitrary units, z-scored
        # in the analysis pipeline anyway)
        vol_values = (vol_values - vol_values.mean()) / vol_values.std()

        for j in range(n_fmri):
            rows.append({
                "subject_id": f"sub-{fmri_indices[j]+1:03d}",
                "roi_name":   roi_name,
                "gm_volume":  round(float(vol_values[j]), 6),
            })

    return pd.DataFrame(rows)


# ===========================================================================
# 3.  MAIN SIMULATION
# ===========================================================================

def main(seed=42):
    """
    Run the full synthetic data generation pipeline.

    Steps:
    1. Generate demographics (age, sex, race).
    2. For each person:
       a. Draw number of quarterly timepoints.
       b. Draw random effects u_sp and u_ps.
       c. Generate contrast factor K and iterate VARX(1) forward.
       d. Apply within-person centering.
    3. For the fMRI subsample (first N_FMRI participants):
       a. Generate ROI BOLD values with embedded correlations.
       b. Generate VBM gray matter volumes.
    4. Save all outputs and ground truth parameters.

    Parameters
    ----------
    seed : int
        Random seed for full reproducibility.
    """
    print(f"Generating synthetic data with seed={seed} ...")
    rng = np.random.default_rng(seed)

    # --- Step 1: Demographics ----------------------------------------------
    n = DEMO["N"]
    demo_df, age_z, sex_c = generate_demographics(rng, n, DEMO)
    print(f"  Demographics: N={n}, "
          f"age={demo_df['age'].mean():.1f} +/- {demo_df['age'].std():.1f}, "
          f"{demo_df['sex'].mean()*100:.1f}% female")

    # --- Step 2: Time series -----------------------------------------------
    n_timepoints = generate_timepoints(rng, n)
    total_transitions = (n_timepoints - 1).sum()
    print(f"  Timepoints: median={int(np.median(n_timepoints))}, "
          f"range=[{n_timepoints.min()}, {n_timepoints.max()}], "
          f"total transitions={total_transitions}")

    # Draw random effects for all participants at once.
    # u_sp_i ~ N(0, tau_sp^2): person-specific deviation in sleep->pain coupling
    # u_ps_i ~ N(0, tau_ps^2): person-specific deviation in pain->sleep coupling
    # These are drawn independently; the model does not assume correlation
    # between the two random effects (they are on different equations).
    u_sp = rng.normal(0, PARAMS["tau_sp"], size=n)
    u_ps = rng.normal(0, PARAMS["tau_ps"], size=n)

    # Iterate over participants and simulate each person's time series
    all_rows = []
    for i in range(n):
        nt = n_timepoints[i]

        # Simulate raw time series
        pain_raw, sleep_raw, contrast_raw = simulate_varx1(
            rng, nt, PARAMS, age_z[i], sex_c[i], u_sp[i], u_ps[i]
        )

        # Apply within-person centering.
        # After this step, each person's mean pain, sleep, and contrast are 0.
        # The estimation model works entirely with these centered values.
        pain_ctr    = within_person_center(pain_raw)
        sleep_ctr   = within_person_center(sleep_raw)
        contrast_ctr = within_person_center(contrast_raw)

        # Store both raw and centered values.
        # The CSV output contains the raw values; the analysis pipeline
        # will re-center them itself.  We save the raw values so that
        # the synthetic data has the same structure as the real data file.
        sid = demo_df.loc[i, "subject_id"]
        for t in range(nt):
            all_rows.append({
                "subject_id":      sid,
                "quarter":         t + 1,  # 1-indexed (quarter 1, 2, ..., 10)
                "pain_severity":   round(float(pain_raw[t]), 4),
                "contrast_factor": round(float(contrast_raw[t]), 4),
                "sleep_quality":   round(float(sleep_raw[t]), 4),
            })

    quarterly_df = pd.DataFrame(all_rows)
    print(f"  Quarterly data: {len(quarterly_df)} rows "
          f"({n} subjects x variable timepoints)")

    # --- Step 3: fMRI subsample --------------------------------------------
    # The fMRI subsample is the first N_FMRI participants.
    # (In the real study, fMRI availability was essentially random with
    # respect to the coupling parameters, so arbitrary selection is fine.)
    fmri_indices = np.arange(N_FMRI)

    roi_df = generate_fmri_rois(rng, N_FMRI, u_sp, fmri_indices)
    vbm_df = generate_vbm_volumes(rng, N_FMRI, u_ps, fmri_indices)
    print(f"  fMRI subsample: N={N_FMRI}, "
          f"{len(FMRI_SP_GAMMAS)} BOLD ROIs, "
          f"{len(VBM_PS_GAMMAS)} VBM ROIs")

    # --- Step 4: Save outputs ----------------------------------------------
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # 4a. Quarterly longitudinal data
    quarterly_path = os.path.join(OUTPUT_DIR, "quarterly_data_long.csv")
    quarterly_df.to_csv(quarterly_path, index=False)
    print(f"  Saved: {quarterly_path}")

    # 4b. Participant demographics
    # Only save the raw demographics (subject_id, age, sex, race).
    # The analysis pipeline computes age_z and sex_c from these.
    demo_path = os.path.join(OUTPUT_DIR, "participants_wideformat.csv")
    demo_df.to_csv(demo_path, index=False)
    print(f"  Saved: {demo_path}")

    # 4c. fMRI ROI values (BOLD)
    roi_path = os.path.join(OUTPUT_DIR, "roi_values.csv")
    roi_df.to_csv(roi_path, index=False)
    print(f"  Saved: {roi_path}")

    # 4d. VBM gray matter volumes
    vbm_path = os.path.join(OUTPUT_DIR, "vbm_volumes.csv")
    vbm_df.to_csv(vbm_path, index=False)
    print(f"  Saved: {vbm_path}")

    # 4e. Ground truth parameters (everything needed to verify recovery)
    ground_truth = {
        "description": (
            "Ground truth parameters used to generate synthetic data. "
            "These are the population-level estimates from the real analysis "
            "(Tables 3-5 of the manuscript) and can be compared against "
            "estimates obtained by fitting the model to this synthetic data."
        ),
        "seed": seed,
        "varx1_fixed_effects": {
            k: v for k, v in PARAMS.items()
            if k not in ("tau_sp", "tau_ps", "sigma_p", "sigma_s", "rho")
        },
        "random_effects": {
            "tau_sp": PARAMS["tau_sp"],
            "tau_ps": PARAMS["tau_ps"],
        },
        "innovations": {
            "sigma_p": PARAMS["sigma_p"],
            "sigma_s": PARAMS["sigma_s"],
            "rho":     PARAMS["rho"],
        },
        "demographics": {
            "N": n,
            "age_mean": round(float(demo_df["age"].mean()), 2),
            "age_sd":   round(float(demo_df["age"].std()), 2),
            "pct_female": round(float(demo_df["sex"].mean()), 3),
            "race_counts": demo_df["race"].value_counts().to_dict(),
        },
        "timepoints": {
            "median":            int(np.median(n_timepoints)),
            "min":               int(n_timepoints.min()),
            "max":               int(n_timepoints.max()),
            "total_transitions": int(total_transitions),
        },
        "fmri_subsample": {
            "N_fmri": N_FMRI,
            "sp_moderation_gammas": FMRI_SP_GAMMAS,
            "sp_embedded_correlations": FMRI_SP_CORR_WITH_U_SP,
            "vbm_ps_moderation_gammas": VBM_PS_GAMMAS,
        },
    }

    truth_path = os.path.join(OUTPUT_DIR, "ground_truth.json")
    with open(truth_path, "w") as f:
        json.dump(ground_truth, f, indent=2)
    print(f"  Saved: {truth_path}")

    # --- Summary statistics for verification --------------------------------
    print("\n  === Verification summary ===")
    print(f"  Pain severity: mean={quarterly_df['pain_severity'].mean():.3f}, "
          f"SD={quarterly_df['pain_severity'].std():.3f}")
    print(f"  Sleep quality:  mean={quarterly_df['sleep_quality'].mean():.3f}, "
          f"SD={quarterly_df['sleep_quality'].std():.3f}")
    print(f"  Contrast:       mean={quarterly_df['contrast_factor'].mean():.3f}, "
          f"SD={quarterly_df['contrast_factor'].std():.3f}")
    print(f"  u_sp SD={u_sp.std():.3f} (target: {PARAMS['tau_sp']:.3f})")
    print(f"  u_ps SD={u_ps.std():.3f} (target: {PARAMS['tau_ps']:.3f})")
    print("\n  Done.")


# ===========================================================================
# 4.  ENTRY POINT
# ===========================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate synthetic data for the sleep-pain coupling pipeline."
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducibility (default: 42)."
    )
    args = parser.parse_args()
    main(seed=args.seed)
