"""Regenerate `codes/python/FUNCTIONS.md` from the code itself.

The registry has to be a TREE mirroring the code — file, then function, then the
functions nested inside it, and class methods under their class — and it has to
be right. Written by hand it drifts within a week; generated, it cannot.

    python tools/make_functions_md.py            # rewrite FUNCTIONS.md
    python tools/make_functions_md.py --check    # exit 1 if it is out of date

The one-line description of each callable is the first line of its docstring, so
"update FUNCTIONS.md" is not a separate chore: writing a docstring IS the entry.
A callable with no docstring shows as `(undocumented)`, which is the point —
the gap is visible in the registry rather than invisible in the source.
"""
from __future__ import annotations

import argparse
import ast
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CODE = os.path.dirname(HERE)
OUT = os.path.join(CODE, "FUNCTIONS.md")

#: (heading, directory relative to CODE, filename filter)
SECTIONS = [
    ("Shared library — `lib/`", "lib", lambda n: True),
    ("Pipeline steps — `codes/python/`", ".",
     lambda n: n.startswith("step") or n in ("run_pipeline.py",
                                             "generate_all_results.py")),
    ("Tools — `tools/`", "tools", lambda n: True),
]

#: not part of the pipeline; one-shot sandbox scripts, kept but not registered
SKIP_DIRS = {"revision", "__pycache__", "archive"}


def summarize(node):
    """First docstring line of a callable, or a visible placeholder."""
    doc = ast.get_docstring(node) or ""
    first = doc.strip().split("\n")[0].strip()
    return first if first else "*(undocumented)*"


def signature(node):
    """`(a, b, *rest, kw, **kwargs)` — names only; defaults are in the source."""
    if isinstance(node, ast.ClassDef):
        return ""
    a = node.args
    names = [x.arg for x in a.posonlyargs + a.args]
    if a.vararg:
        names.append("*" + a.vararg.arg)
    names += [x.arg for x in a.kwonlyargs]
    if a.kwarg:
        names.append("**" + a.kwarg.arg)
    return "(" + ", ".join(names) + ")"


def walk(node, depth, lines):
    """Emit one bullet per callable, indented by nesting depth."""
    for child in node.body:
        if not isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef,
                                  ast.ClassDef)):
            continue
        tag = "class " if isinstance(child, ast.ClassDef) else ""
        lines.append(f"{'  ' * depth}- {tag}`{child.name}{signature(child)}` — "
                     f"{summarize(child)}")
        walk(child, depth + 1, lines)


def render():
    """The whole registry as one Markdown string."""
    lines = [
        "# Function registry",
        "",
        "Every callable in the pipeline, as a tree: file, then its functions, then",
        "anything nested inside them. Consult it BEFORE writing a new function —",
        "if the concept is already here, reuse or generalize it rather than adding",
        "a second copy.",
        "",
        "Generated by `tools/make_functions_md.py` from the docstrings themselves.",
        "Do not edit by hand; run the tool.",
        "",
    ]
    for heading, rel, keep in SECTIONS:
        d = os.path.normpath(os.path.join(CODE, rel))
        lines += [f"## {heading}", ""]
        for fn in sorted(os.listdir(d)):
            if not fn.endswith(".py") or not keep(fn):
                continue
            path = os.path.join(d, fn)
            if any(part in SKIP_DIRS for part in path.split(os.sep)):
                continue
            try:
                tree = ast.parse(open(path).read())
            except SyntaxError as exc:
                lines += [f"### `{fn}`", "", f"  *(does not parse: {exc})*", ""]
                continue
            doc = (ast.get_docstring(tree) or "").strip().split("\n")[0]
            body = []
            walk(tree, 0, body)
            lines += [f"### `{fn}`", "", f"{doc}", ""]
            lines += body if body else ["*(no callables)*"]
            lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if FUNCTIONS.md is out of date, write nothing")
    args = ap.parse_args()

    text = render()
    if args.check:
        current = open(OUT).read() if os.path.exists(OUT) else ""
        if current == text:
            print("FUNCTIONS.md is up to date")
            return 0
        print("FUNCTIONS.md is OUT OF DATE — run: python tools/make_functions_md.py")
        return 1

    with open(OUT, "w") as fh:
        fh.write(text)
    n = sum(1 for line in text.split("\n") if line.lstrip().startswith("- "))
    print(f"wrote {os.path.relpath(OUT, os.path.dirname(CODE))} — {n} callables")
    return 0


if __name__ == "__main__":
    sys.exit(main())
